version: '3.8'
services:
  driving-school-service:
    container_name: driving-school-service
    image: node:18.0.0-alpine3.14
    working_dir: /src/app
    ports:
      - 3000:3000
    volumes:
      - ../:/src/app
    command: sh -c "$CMD"
  driving-school-database:
    container_name: driving-school-database
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: driving-school
    ports:
      - "27017:27017"